#!/bin/bash

mkdir /var/www
mkdir /var/www/phpmyadmin
mkdir /var/www/wordpress
mkdir /var/www/grafana

[ -z "$SSH_USER" ] && SSH_USER=admin

adduser --disabled-password --gecos "" "$SSH_USER"
[ -s "$SSH_PASSWORD" ] && usermod --password "$SSH_PASSWORD" "$SSH_USER"

service ssh start

/usr/sbin/nginx -g 'daemon off;'
